version: '2'

services:
    ikev2:
        build: https://github.com/kerberjg/docker-vpn-ikev2-roadwarrior.git#develop
        networks: 
            vpcbr:
                ipv4_address: 172.20.0.10
        env_file:
            - ./data/ikev2.env
        environment:
            - TZ
            - SHARED_SECRET
            - HOST_ADDR
            - VPN_SUBNET
            - VPN_SUBNET_IP6
            - DNS_SERVER1=172.20.0.9
            - DNS_SERVER2=172.20.0.9
            - HOST_FQDN
            - CONN_NAME
        ports:
            - "4500:4500/udp"
            - "500:500/udp"
        cap_add:
            - NET_ADMIN
        restart: always

    wireguard:
        image: ghcr.io/linuxserver/wireguard
        networks: 
            vpcbr:
                ipv4_address: 172.20.0.11
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        env_file:
            - ./data/ikev2.env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ
            - INTERNAL_SUBNET
            - SERVERURL
            - SERVERPORT=51820
            - PEERDNS=172.20.0.9
            - ALLOWEDIPS=0.0.0.0/0,::/0
        volumes:
            - ./data/wireguard-config:/config
            - /lib/modules:/lib/modules
        ports:
            - 51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped

    dns:
        image: pihole/pihole:latest
        networks: 
            vpcbr:
                ipv4_address: 172.20.0.9
        environment:
            - TZ
            - DNS1=1.1.1.1
            - DNS2=1.0.0.1
            - DNSSEC=true
            - VIRTUAL_HOST=pi.hole
        volumes:
            - './data/etc-pihole/:/etc/pihole/'
            - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        expose:
            - "53"
            - "53"
            - "67"
            - "80"
            - "443"
        restart: always

    # TODO: wireguard

    # TODO: webportal

    # TODO(optional): authserver

networks:
    vpcbr:
        driver: bridge
        ipam: 
            config: 
                - subnet: 172.20.0.0/16
                  gateway: 172.20.0.1